name: CI/CD

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
#Job 1: Build & Test
  build-and-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository and add Java
        uses: actions/checkout@v4
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
          cache: 'maven'
          
      - name: Run and Test with Maven - Product Service
        run:  mvn package
        working-directory: product-service

      # - name: Build Docker image
      #   run: docker build -t productservice .
      #   working-directory: product-service

      - name: Run and Test with Maven - Order Service
        run:  mvn package
        working-directory: order-service
 
        
      # - name: Build Docker image
      #   run: docker build -t orderservice .
      #   working-directory: order-service

      #Test
      -   name: Upload test report artifact
          uses: actions/upload-artifact@v4
          with:
           name: test-reports
           path: **/target/surefire-reports/*.xml # Path to the generated test results
          if: always() # Upload artifacts even if tests fail
          
      
  #Job 2: Docker Build & Integration Test
  docker-build-integration-tests:
  
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Docker Build and Integration Tests
      uses: actions/checkout@v4
      
    - name: Build Product Docker image
      run: docker build -t productservice .
      #OR this if above doesnt work, from template.. run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      working-directory: order-service
      
    - name: Build Order Docker image
      run: docker build -t productservice .
      working-directory: product-service
      
    - name: Start Docker Compose
      run: docker-compose up -d

      #Add something for Wait for all services to be healthy

   #Initialize feature flags in Unleash using API calls
    - name: Initialize feature flags 
      run: ./scripts/init-flags.sh

   #Add Run integration tests that verify:
#–	Feature flags can be toggled via Unleash API
# –	premium-pricing flag correctly affects /api/products/premium response
# –	order-notifications flag correctly affects order creation logging
# –	bulk-order-discount flag correctly affects order pricing

    - name: Tear Down Docker Compose
      run: docker-compose down
      
#Job 3: Feature Flag Validation
 docker-feature-flag-validation:
  
    runs-on: ubuntu-latest
    needs: docker-build-integration-tests
    steps:
    - name: Feature Flag Validation
      uses: actions/checkout@v4
    # - name: Test Feature Flag Toggle
    #  run: |
     
      

      # - name: Docker Compose
      #   run: docker compose up 

      # - name: Docker compose down
      #   run: docker compose down
        
      # - name: Wait for Healthcheck to run
      #   run: Start-Sleep -s 30
        
  

  
